### ISSUE TITLE
Exception when rendering any page

### ISSUE THREAD

**Issue by akatasonov** [TryGhost/Ghost#9190]
### Issue Summary

Ghost is not working (node index produces an exception and dies) after upgrading to 1.15.0

### Steps to Reproduce

1. Upgrade to 1.15.0
2. Navigating to any pages results in: 

```
Oct 29 23:33:45 katasonov ghost[22840]: > ghost@1.15.0 start /home/ghost/happy-chance.com
Oct 29 23:33:45 katasonov ghost[22840]: > node index
Oct 29 23:33:46 katasonov ghost[22840]: /home/ghost/happy-chance.com/core/server/config/index.js:4
Oct 29 23:33:46 katasonov ghost[22840]:     debug = _debug('ghost:config'),
Oct 29 23:33:46 katasonov ghost[22840]:             ^
Oct 29 23:33:46 katasonov ghost[22840]: TypeError: _debug is not a function
Oct 29 23:33:46 katasonov ghost[22840]:     at Object.<anonymous> (/home/ghost/happy-chance.com/core/server/config/index.js:4:13)
Oct 29 23:33:46 katasonov ghost[22840]:     at Module._compile (module.js:570:32)
Oct 29 23:33:46 katasonov ghost[22840]:     at Object.Module._extensions..js (module.js:579:10)
Oct 29 23:33:46 katasonov ghost[22840]:     at Module.load (module.js:487:32)
Oct 29 23:33:46 katasonov ghost[22840]:     at tryModuleLoad (module.js:446:12)
Oct 29 23:33:46 katasonov ghost[22840]:     at Function.Module._load (module.js:438:3)
Oct 29 23:33:46 katasonov ghost[22840]:     at Module.require (module.js:497:17)
Oct 29 23:33:46 katasonov ghost[22840]:     at require (internal/module.js:20:19)
Oct 29 23:33:46 katasonov ghost[22840]:     at Object.<anonymous> (/home/ghost/happy-chance.com/core/server/index.js:18:14)
Oct 29 23:33:46 katasonov ghost[22840]:     at Module._compile (module.js:570:32)
Oct 29 23:33:46 katasonov ghost[22840]: npm ERR! Linux 3.14.79-115
Oct 29 23:33:46 katasonov ghost[22840]: npm ERR! argv "/usr/local/bin/node" "/usr/bin/npm" "start" "--production"
Oct 29 23:33:46 katasonov ghost[22840]: npm ERR! node v6.10.3
Oct 29 23:33:46 katasonov ghost[22840]: npm ERR! npm  v3.10.10
Oct 29 23:33:46 katasonov ghost[22840]: npm ERR! code ELIFECYCLE
Oct 29 23:33:46 katasonov ghost[22840]: npm ERR! ghost@1.15.0 start: `node index`
Oct 29 23:33:46 katasonov ghost[22840]: npm ERR! Exit status 1
Oct 29 23:33:46 katasonov ghost[22840]: npm ERR!
Oct 29 23:33:46 katasonov ghost[22840]: npm ERR! Failed at the ghost@1.15.0 start script 'node index'.
Oct 29 23:33:46 katasonov ghost[22840]: npm ERR! Make sure you have the latest version of node.js and npm installed.
Oct 29 23:33:46 katasonov ghost[22840]: npm ERR! If you do, this is most likely a problem with the ghost package,
Oct 29 23:33:46 katasonov ghost[22840]: npm ERR! not with npm itself.
Oct 29 23:33:46 katasonov ghost[22840]: npm ERR! Tell the author that this fails on your system:
Oct 29 23:33:46 katasonov ghost[22840]: npm ERR!     node index
Oct 29 23:33:46 katasonov ghost[22840]: npm ERR! You can get information on how to open an issue for this project with:
Oct 29 23:33:46 katasonov ghost[22840]: npm ERR!     npm bugs ghost
Oct 29 23:33:46 katasonov ghost[22840]: npm ERR! Or if that isn't available, you can get their info via:
Oct 29 23:33:46 katasonov ghost[22840]: npm ERR!     npm owner ls ghost
Oct 29 23:33:46 katasonov ghost[22840]: npm ERR! There is likely additional logging output above.
Oct 29 23:33:46 katasonov ghost[22840]: npm ERR! Please include the following file with any support request:
Oct 29 23:33:46 katasonov ghost[22840]: npm ERR!     /home/ghost/happy-chance.com/npm-debug.log
Oct 29 23:33:46 katasonov systemd[1]: ghost-happy-chance.com.service: Main process exited, code=exited, status=1/FAILURE
Oct 29 23:33:46 katasonov systemd[1]: ghost-happy-chance.com.service: Unit entered failed state.
Oct 29 23:33:46 katasonov systemd[1]: ghost-happy-chance.com.service: Failed with result 'exit-code'.
Oct 29 23:33:46 katasonov systemd[1]: ghost-happy-chance.com.service: Service hold-off time over, scheduling restart.
```

Contents of the npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/bin/npm', 'start', '--production' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ghost@1.15.0~prestart: ghost@1.15.0
6 silly lifecycle ghost@1.15.0~prestart: no script for prestart, continuing
7 info lifecycle ghost@1.15.0~start: ghost@1.15.0
8 verbose lifecycle ghost@1.15.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle ghost@1.15.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/ghost/happy-chance.com/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle ghost@1.15.0~start: CWD: /home/ghost/happy-chance.com
11 silly lifecycle ghost@1.15.0~start: Args: [ '-c', 'node index' ]
12 silly lifecycle ghost@1.15.0~start: Returned: code: 1  signal: null
13 info lifecycle ghost@1.15.0~start: Failed to exec start script
14 verbose stack Error: ghost@1.15.0 start: `node index`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid ghost@1.15.0
16 verbose cwd /home/ghost/happy-chance.com
17 error Linux 3.14.79-115
18 error argv "/usr/local/bin/node" "/usr/bin/npm" "start" "--production"
19 error node v6.10.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error ghost@1.15.0 start: `node index`
22 error Exit status 1
23 error Failed at the ghost@1.15.0 start script 'node index'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ghost package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node index
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ghost
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ghost
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

### Technical details:

* Ghost Version: 1.15.0
* Node Version: v6.10.3
* Browser/OS: Chrome 61/OS X Sierra
* Database: sqlite

**Comment by acburdine** [comment]
@akatasonov My initial guess here is that your dependencies are out of date - have you tried running `npm install --production` and then `npm start --production`?

**Comment by akatasonov** [comment]
@acburdine yes I did run ```npm install --production`` and restarted the service: it does not help

**Comment by acburdine** [comment]
Hmm okay. Would you be willing to try removing your node_modules folder and re-running `npm install --production`? `rm -rf node_modules && npm install --production`.

Or, better yet, use Yarn to install dependencies - we switched to Yarn with ghost 1.0 because of issues like this that we were having with npm. `rm -rf node_modules && yarn install --production`

**Comment by kirrg001** [comment]
We're sorry to hear you're having problems, but please do not use our GitHub repo for support. Please read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). You can always use our [slack](https://slack.ghost.org/) community - https://slack.ghost.org. This sounds like a installation/dependency problem and not like a Ghost bug. Closing.

**Comment by akatasonov** [comment]
@kirrg001 not sure why it sounds like an installation/dependency problem to you. I have been running Ghost for longer than a year and upgraded to each version without any issues.
Moreover, I have tried removing node_modules and reinstalling them with both the ```npm``` and ```yarn``` and it does not fix the issue.
I have even wiped node_modules, downloaded the latest build and overwritten the existing installation once more, did ```yarn install --production```. The problem is still there.

**Comment by akatasonov** [comment]
@acburdine @kirrg001 actually the error is different now, but still doesn't look like "installation problem":

```
Oct 30 15:53:19 katasonov ghost[32447]: /home/ghost/happy-chance.com/node_modules/knex-migrator/lib/index.js:22
Oct 30 15:53:19 katasonov ghost[32447]:             throw new errors.KnexMigrateError({
Oct 30 15:53:19 katasonov ghost[32447]:             ^
Oct 30 15:53:19 katasonov ghost[32447]: InternalServerError: Please provide a file named MigratorConfig.js in your project root.
Oct 30 15:53:19 katasonov ghost[32447]:     at new KnexMigrateError (/home/ghost/happy-chance.com/node_modules/knex-migrator/lib/errors.js:9:26)
Oct 30 15:53:19 katasonov ghost[32447]:     at new KnexMigrator (/home/ghost/happy-chance.com/node_modules/knex-migrator/lib/index.js:22:19)
Oct 30 15:53:19 katasonov ghost[32447]:     at Object.healthCheck [as check] (/home/ghost/happy-chance.com/core/server/data/db/health.js:7:24)
Oct 30 15:53:19 katasonov ghost[32447]:     at init (/home/ghost/happy-chance.com/core/server/index.js:46:21)
Oct 30 15:53:19 katasonov ghost[32447]:     at makeGhost (/home/ghost/happy-chance.com/core/index.js:11:12)
Oct 30 15:53:19 katasonov ghost[32447]:     at Object.<anonymous> (/home/ghost/happy-chance.com/index.js:21:1)
Oct 30 15:53:19 katasonov ghost[32447]:     at Module._compile (module.js:570:32)
Oct 30 15:53:19 katasonov ghost[32447]:     at Object.Module._extensions..js (module.js:579:10)
Oct 30 15:53:19 katasonov ghost[32447]:     at Module.load (module.js:487:32)
Oct 30 15:53:19 katasonov ghost[32447]:     at tryModuleLoad (module.js:446:12)
Oct 30 15:53:19 katasonov ghost[32447]:     at Function.Module._load (module.js:438:3)
Oct 30 15:53:19 katasonov ghost[32447]:     at Module.runMain (module.js:604:10)
Oct 30 15:53:19 katasonov ghost[32447]:     at run (bootstrap_node.js:390:7)
Oct 30 15:53:19 katasonov ghost[32447]:     at startup (bootstrap_node.js:150:9)
Oct 30 15:53:19 katasonov ghost[32447]:     at bootstrap_node.js:505:3
Oct 30 15:53:20 katasonov systemd[1]: ghost-katasonov.com.service: Service hold-off time over, scheduling restart.

```
