### PR TITLE
🐛   Skipped image optimization when input image is smaller byte size than optimized one

### LINKED ISSUE #10144: Pre-optimized image size increases after upload
### Issue Summary

When uploading a pre-optimized image to Ghost, its size is sometimes increased. Samples:
- The image is being uploaded: https://d.pr/i/76ZVry
- Output, higher size image: https://d.pr/i/FPGvW2

### To Reproduce

1. Upload the image that had its quality set to lower than the default (80%)
2. Check the processed image size, in this case, increase from ~120kB to ~650kB 

### Technical details:

* Ghost Version: 2.5.0
* Node Version: v8.11.4
* Browser/OS: Ubuntu/Linux
* Database: MySQL 5.7.24

### PR DESCRIPTION
**Pull request by naz**
closes #10144

- When the input image is well optimized and has a smaller byte size than the processed one it's still being used
- Bumped sharp version to have access to `size` property

### CODE REVIEW

File: core/server/lib/image/manipulator.js [hunk 1]
```diff
@@ -8,15 +9,22 @@ const common = require('../common');
...
         // @NOTE: workaround for Windows as libvips keeps a reference to the input file
         //        which makes it impossible to fs.unlink() it on cleanup stage
         sharp.cache(false);
-        img = sharp(options.in);
+
+        init = fs.readFile(options.in)
+            .then((data) => {
+                originalData = data;
+
+                // @NOTE: have to user constructor with Buffer for sharp to be able to expose size property
```
Comment (kirrg001) [inline core/server/lib/image/manipulator.js]: > have to user constructor

have to use ...

---

Just pointing this out, because i head to read this line 2 times to understand what you mean 🙊

Comment (gargol) [reply core/server/lib/image/manipulator.js]: :see_no_evil: oh noooo!

File: core/server/lib/image/manipulator.js [hunk 2]
```diff
@@ -8,15 +9,22 @@ const common = require('../common');
...
+                img = sharp(data);
+            });
```
Comment (kirrg001) [inline core/server/lib/image/manipulator.js]: This becomes a little hard to read, because the try/catch is now used for sync and async code 🤔

File: core/server/lib/image/manipulator.js [hunk 3]
```diff
@@ -25,18 +33,26 @@ const process = (options = {}) => {
...
             // CASE: if you call `rotate` it will automatically remove the orientation (and all other meta data) and rotates
             //       based on the orientation. It does not rotate if no orientation is set.
             img.rotate();
+            return img.toBuffer({resolveWithObject: true});
         })
-        .then(() => {
-            return img.toFile(options.out);
+        .then(({data, info}) => {
+            if (info.size > originalSize) {
+                return fs.writeFile(options.out, originalData);
```
Comment (kirrg001) [inline core/server/lib/image/manipulator.js]: Understanding question: we can't know if this case becomes true before manipulating the image, right?

Comment (gargol) [reply core/server/lib/image/manipulator.js]: Yes, that's exactly the case

File: package.json [hunk 4]
```diff
@@ -101,7 +101,7 @@
     "xml": "1.0.1"
   },
   "optionalDependencies": {
-    "sharp": "0.20.7",
+    "sharp": "0.21.0",
```
Comment (gargol) [inline package.json]: The reason for bump - http://sharp.pixelplumbing.com/en/stable/changelog/#v0210-4th-october-2018, `size` attribute has been introduced in this version which makes image size calculation easier.

File: core/server/lib/image/manipulator.js (hunk 2 above)
Comment (gargol) [reply core/server/lib/image/manipulator.js]: 100% agree. Have refactored it into a more readable piece of code :)

**Comment by gargol** [comment]
@kirrg001 would be great if you could run a quick test on OSX/Windows for this branch. Only checked on Linux

File: core/server/lib/image/manipulator.js (hunk 3 above)
Comment (kirrg001) [reply core/server/lib/image/manipulator.js]: Ok cool 👍

**Comment by kirrg001** [comment]
> @kirrg001 would be great if you could run a quick test on OSX/Windows for this branch. Only checked on Linux

Will do later :)

File: package.json (hunk 4 above)
Comment (kirrg001) [reply package.json]: > Requires libvips v8.7.0.

What does that mean exactly?
Does it mean 0.21.0 no longer works with < 8.7.0?

**Comment by kirrg001** [comment]
> @kirrg001 would be great if you could run a quick test on OSX/Windows for this branch. Only checked on Linux

Looks like it's working 👍 
I checked out your branch, ran `yarn`, sharp was reinstalled/rebuild/downloaded and then i uploaded an image.

**Comment by kirrg001** [comment]
Hm i switched back to master, ran `yarn` and got for upload API test

```
    success cases
dyld: lazy symbol binding failed: Symbol not found: __ZN4vips6VImage7pngsaveEPcPNS_7VOptionE
  Referenced from: /Users/kirrg001/dev/ghost/ghost-workspace2/node_modules/sharp/build/Release/sharp.node
  Expected in: /Users/kirrg001/dev/ghost/ghost-workspace2/node_modules/sharp/build/Release/../../vendor/lib/libvips-cpp.42.dylib

dyld: Symbol not found: __ZN4vips6VImage7pngsaveEPcPNS_7VOptionE
  Referenced from: /Users/kirrg001/dev/ghost/ghost-workspace2/node_modules/sharp/build/Release/sharp.node
  Expected in: /Users/kirrg001/dev/ghost/ghost-workspace2/node_modules/sharp/build/Release/../../vendor/lib/libvips-cpp.42.dyli
```

Maybe a local problem, but wanted to share.

File: package.json (hunk 4 above)
Comment (gargol) [reply package.json]: My understanding it's just version of binaries that are pinned to a specific release, basing on [this](http://sharp.pixelplumbing.com/en/stable/install/#linux):
> libvips and its dependencies are fetched and stored within node_modules/sharp/vendor during npm install. This involves an automated HTTPS download of approximately 8MB.

and how version installation is handled around [here](https://github.com/lovell/sharp/blob/master/install/libvips.js#L75)

Comment (kirrg001) [reply package.json]: Thanks. It probably only breaks if 

>  const useGlobalLibvips = libvips.useGlobalLibvips();

Is true. That means you are using a global libvips installation? And you dont have 8.7.0 installed.

**Review by kirrg001 — APPROVED** [review]
👍 Merge if you feel confident that the sharp version bump does not break anything.

**Comment by kirrg001** [comment]
> Skipped image optimization when input image is smaller byte size than optimized one

Commit message probably needs an emoji.

e.g. 🐛  Fixed image optimisation for input image being smaller than optimized one

**Comment by gargol** [comment]
The version bump does seem to install properly even when having old version of libvips cached by npm cache. It just takes a bit more time to download new binaries. As for changes in the library itself, minor version changes didn't affect us. Merging! :tada:
