### ISSUE TITLE
Upgrade from Ghost 0.8 to 0.9 fail (lodash module)

### ISSUE THREAD

**Issue by stylersnico** [TryGhost/Ghost#7161]
Hi everyone,

After upgrade from 0.8 to 0.9 Ghost won't start anymore.

```bash
ghost@---:/var/www/ghost/ NODE_ENV=production FORCE_MIGRATION=true npm start index.js

> ghost@0.9.0 start /var/www/ghost/
> node index "index.js"

WARNING: Ghost is attempting to use a direct method to send email.
It is recommended that you explicitly configure an email service.
Help and documentation can be found at http://support.ghost.org/mail.


ERROR: Cannot find module 'lodash/object/assign'

 Error: Cannot find module 'lodash/object/assign'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/ghost/node_modules/knex/lib/raw.js:8:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/ghost/node_modules/knex/lib/index.js:3:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/ghost/node_modules/knex/knex.js:8:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

```

`npm install lodash` doesn't solve this problem.

Any idea?

Thanks

**Comment by acburdine** [comment]
hey @stylersnico, please see #7158 for the solution to this. Thanks!
