### ISSUE TITLE
Internal server error, cannot upload image.   

### ISSUE THREAD

**Issue by minovc3** [TryGhost/Ghost#16278]
### Issue Summary

It is not possible to upload images into a post after building a docker image with Ghost 5.34.0, while this was not an issue with prior versions of Ghost 5.33.8 and 5.33.7. Compiled all 3 images from scratch with no cache option on the same box and had always the issue with Ghost 5.34.0.  Reproduced in a docker environment on ARM using the official Debian docker compose file. 

### Steps to Reproduce

Compiled a docker image with Ghost 5.34.0, mounted a local path 
`  volumes:
      - /var/www/mghost/volumes/ghost_minov_it_data:/var/lib/ghost/content`
      
Tried to upload an image via GUI

### Ghost Version

5.34.0

### Node.js Version

node:16-bullseye-slim

### How did you install Ghost?

Compiled via docker using the Debian image 

### Database type

MySQL 8

### Browser & OS version

Tried from Chrome and Safari 

### Relevant log / error output

```shell
[2023-02-15 18:52:49] ERROR "POST /ghost/api/admin/images/upload/" 500 2094ms
An unexpected error occurred, please try again.
"store.urlToPath is not a function"
Error ID:
    f19dd880-ad61-11ed-a927-7b5476df5eb2
Error Code: 
    UNEXPECTED_ERROR
----------------------------------------
TypeError: store.urlToPath is not a function
    at module.exports.prepareError (/var/lib/ghost/versions/5.34.0/node_modules/@tryghost/mw-error-handler/lib/mw-error-handler.js:92:19)
    at Object.query (/var/lib/ghost/versions/5.34.0/core/server/api/endpoints/images.js:40:50)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /var/lib/ghost/versions/5.34.0/node_modules/@tryghost/api-framework/lib/http.js:64:28
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
@minovc3 Do you happen to use a custom storage adapter?

**Comment by minovc3** [comment]
> @minovc3 Do you happen to use a custom storage adapter?

Hi there. Yes! Tried with two different storage adapters: 
1. https://github.com/kevinlang/ghost-storage-b2
2. https://github.com/colinmeinke/ghost-storage-adapter-s3

Neither of them worked on version 5.34.0, but both of them have been working on 5.33.8 and earlier versions of Ghost. I have been using them since Ghost 5.X without any issues.
